"""S1 — operator intake: turn the questionnaire into a validated scope config.

    python -m ui_discovery.intake                 # interactive
    python -m ui_discovery.intake --template      # blank annotated config
    python -m ui_discovery.intake --check scope.yaml

This is the scoping front door. `INTAKE_QUESTIONNAIRE.md` is the human form;
this produces the machine-readable `scope.yaml` the commands consume, and it
is the audit record of what was in scope and why.

The interactive path asks only the questions that change a run. Everything
else keeps its default and can be edited into the file afterwards — a
fifty-question interrogation is a good way to make people skip scoping
entirely.
"""

from __future__ import annotations

import argparse
import sys
from typing import Optional

from .config import (
    AuthSettings,
    Budget,
    Capabilities,
    Module,
    ProbeSettings,
    Identity,
    Outputs,
    Privacy,
    Safety,
    Scope,
    ScopeRules,
    dump_scope,
    load_scope,
)

TEMPLATE_HEADER = """\
# Scope config for the UI Discovery Engine.
#
# Generated by `python -m ui_discovery.intake`. Keep it beside the run: it is
# both the input to every command (`--config scope.yaml`) and the record of
# what was in scope and why.
#
# Rule zero — authorization. Only run against applications you are explicitly
# permitted to crawl and test.
#
# Consumed by:  crawl · extract · probe  (flags override anything here)
"""


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        answer = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        return default
    return answer or default


def _ask_bool(prompt: str, default: bool = False) -> bool:
    raw = _ask(f"{prompt} (y/n)", "y" if default else "n").lower()
    return raw.startswith("y")


def _ask_list(prompt: str) -> list[str]:
    raw = _ask(f"{prompt} (comma-separated, blank for none)")
    return [item.strip() for item in raw.split(",") if item.strip()]


def build_interactively() -> Scope:
    print("\n" + "=" * 68)
    print("Operator intake — scoping a run")
    print("Only run against applications you are explicitly permitted to test.")
    print("Press Enter to accept the default shown in brackets.")
    print("=" * 68 + "\n")

    print("-- Target ------------------------------------------------------")
    target = _ask("Product / app name")
    start_url = _ask("Start URL")
    environment = _ask("Environment (prod/staging/sandbox)", "staging")

    print("\n-- Authorization -----------------------------------------------")
    authorized = _ask_bool("Are you authorized to test this target?", True)
    authorized_by = _ask("Who approved it") if authorized else ""

    print("\n-- Scope -------------------------------------------------------")
    include = _ask_list("In-scope path patterns, e.g. /app/**")
    exclude = _ask_list("Out-of-scope path patterns, e.g. /admin/**,/logout")

    print("\n-- Budget ------------------------------------------------------")
    max_pages = int(_ask("Max pages", "25") or 25)
    max_depth = int(_ask("Max depth", "3") or 3)

    print("\n-- Authentication ----------------------------------------------")
    auth_required = _ask_bool("Does the target require login?", False)
    state_file = _ask("Saved session file", "session.json") if auth_required else None

    print("\n-- Application behaviour ---------------------------------------")
    hash_routes = _ask_bool("Is it a hash-routed SPA (#/route)?", False)
    dedupe_queries = _ask_bool("Collapse tracking/query-noise variants?", True)

    print("\n-- Capture -----------------------------------------------------")
    screenshots = _ask_bool("Capture screenshots?", True)
    probe = _ask_bool(
        "Interact with the app — open modals, menus and tabs safely?", True)
    tab_exclude: list[str] = []
    if probe:
        # Asked because it is the setting most likely to matter and least
        # likely to be discovered: opening one heavy tab on sixty screens is
        # sixty slow clicks nobody wanted.
        tab_exclude = _ask_list(
            "Tabs that should never be opened (e.g. Audit Log)")

    print("\n-- Safety ------------------------------------------------------")
    never_touch = _ask_list("Controls that must NEVER be interacted with")
    block_extra = _ask_list("Extra destructive words to refuse")

    print("\n-- Outputs -----------------------------------------------------")
    out_dir = _ask("Artifact root (blank = your Downloads folder)", "")
    keep_history = _ask_bool("Keep one folder per run (needed to diff)?", False)

    return Scope(
        target=target,
        start_url=start_url or None,
        environment=environment or None,
        authorized=authorized,
        authorized_by=authorized_by or None,
        scope=ScopeRules(include=include, exclude=exclude),
        auth=AuthSettings(required=auth_required, state_file=state_file),
        budget=Budget(max_pages=max_pages, max_depth=max_depth),
        identity=Identity(dedupe_queries=dedupe_queries, hash_routes=hash_routes),
        capabilities=Capabilities(screenshots=screenshots, probe=probe),
        probe=ProbeSettings(tab_exclude=tab_exclude),
        safety=Safety(never_touch=never_touch, block_words_extra=block_extra),
        privacy=Privacy(),
        outputs=Outputs(dir=out_dir, keep_history=keep_history,
                        run_label=target or None),
    )


def build_template() -> Scope:
    """A filled-in example, so the file teaches its own schema."""
    return Scope(
        target="acme-portal",
        start_url="https://portal.acme.example/",
        environment="staging",
        authorized=True,
        authorized_by="",
        known_endpoints=["GET /api/v1/accounts"],
        scope=ScopeRules(include=["/app/**"],
                         exclude=["/admin/**", "/billing/**", "/logout"]),
        auth=AuthSettings(required=True, state_file="session.json"),
        budget=Budget(),
        identity=Identity(dedupe_queries=True, drop_params=["tab"]),
        capabilities=Capabilities(),
        # Probing is on by default. This block is how you scope it down: the
        # top level sets the norm, and a module states only what differs.
        probe=ProbeSettings(tabs="all", tab_exclude=["Audit Log"]),
        modules=[
            Module(name="Orders", start_url="https://portal.acme.example/orders",
                   probe=ProbeSettings(max_interactions=60, tabs="listed",
                                       tab_labels=["Overview", "Activity"])),
            Module(name="Reports", start_url="https://portal.acme.example/reports",
                   probe=ProbeSettings(enabled=False)),
        ],
        safety=Safety(block_words_extra=["deactivate account"],
                      never_touch=["#danger-zone"]),
        privacy=Privacy(redact_network_keys=["account", "ssn"]),
        outputs=Outputs(keep_history=True, run_label="acme-portal"),
    )


def audit(scope: Scope, path: str) -> list[str]:
    """Report anything about a scope config that an operator should look at
    twice. Warnings, not errors — the engine records scope, it cannot verify
    authorization."""
    notes: list[str] = []
    if scope.authorized is not True:
        notes.append("authorized is not true — confirm you are permitted to "
                     "run against this target.")
    if scope.authorized and not scope.authorized_by:
        notes.append("authorized_by is empty — record who approved this run.")
    if (scope.environment or "").lower() in ("prod", "production"):
        notes.append("environment is prod — prefer a non-production target.")
    if not scope.start_url and not scope.modules:
        notes.append("no start_url and no modules — every command will need a "
                     "URL on the command line.")
    if scope.auth.required and not scope.auth.state_file:
        notes.append("auth.required is true but no auth.state_file is set.")
    if scope.outputs.keep_history is False:
        notes.append("outputs.keep_history is false — re-runs overwrite the "
                     "previous snapshot, leaving nothing for `diff` to "
                     "compare.")
    return notes


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="ui_discovery.intake",
        description="Operator intake -> validated scope config (S1).",
    )
    parser.add_argument(
        "--output", "-o", default="scope.yaml",
        help="Where to write the config (.yaml or .json). Default: scope.yaml",
    )
    parser.add_argument(
        "--template", action="store_true",
        help="Write a filled-in example config instead of prompting.",
    )
    parser.add_argument(
        "--check", metavar="FILE", default=None,
        help="Validate an existing config and report scope concerns.",
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Overwrite the output file if it already exists.",
    )
    args = parser.parse_args(argv)

    if args.check:
        try:
            scope = load_scope(args.check)
        except (FileNotFoundError, ValueError) as exc:
            print(f"[ERROR] {exc}", file=sys.stderr)
            return 1
        print(f"[INFO] {args.check} is a valid scope config"
              + (f" (target: {scope.target})" if scope.target else ""))
        notes = audit(scope, args.check)
        for note in notes:
            print(f"[WARN] {note}", file=sys.stderr)
        return 0

    from pathlib import Path

    out = Path(args.output)
    if out.exists() and not args.force:
        print(f"[ERROR] {out} already exists. Pass --force to overwrite, or "
              f"choose another --output.", file=sys.stderr)
        return 1

    scope = build_template() if args.template else build_interactively()
    path = dump_scope(scope, str(out))

    # Prepend the explanatory header for YAML (JSON has no comments).
    if out.suffix.lower() in (".yaml", ".yml"):
        out.write_text(TEMPLATE_HEADER + "\n" + out.read_text(encoding="utf-8"),
                       encoding="utf-8")

    print(f"\n[INFO] Wrote {path}")
    for note in audit(scope, path):
        print(f"[WARN] {note}", file=sys.stderr)
    print(f"[INFO] Use it:  python -m ui_discovery.crawl --config {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
